### ISSUE TITLE
Include nested parse for `ref` role text

### ISSUE THREAD

**Issue by rossbar** [executablebooks/MyST-Parser#115]
**Describe the bug**
`` {ref}`*vectorization* <sec:vectorization>` `` should result in "vectorization" as a link *and* italicized. The current result is:
```html
<a class="reference internal" href="ch1.html#sec-vectorization"><span class="std std-ref">*vectorization*</span></a>.</p>
```

**To Reproduce**
To use an example already at hand:
1. Open to `docs/examples/wealth_dynamics_md.md`
2. Modify the area around line 56 to add a label and a reference:
```
(sec:lorenz)=                                                                   
## Lorenz Curves and the Gini Coefficient                                       
                                                                                
Here is a reference to {ref}`*Lorenz* <sec:lorenz>`, with emphasis!
```
3. Navigate to `docs/` and build: `make html`
4. View the output: `<browser> _build/html/examples/wealth_dynamics_md.html`

**Expected behavior**
The emphasis syntax within a role should result in a functioning link that is also italicized.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Python Version [e.g. 3.7.1] 3.8.2
 - Package Version [e.g. 0.1.0] MyST-Parser 0.5.1

**Additional context**
I noticed that `tests/test_syntax/test_ast.py` has a `test_role` which appears to test internal emphasis. I'm not as familiar with `pytest` as I need to be, so I had trouble parsing the test suite to figure out exactly what was happening - either way, it doesn't appear the test covers the full conversion from MyST syntax->HTML.

**Comment by chrisjsewell** [comment]
Thanks for the feedback @rossbar 👍 

> I noticed that tests/test_syntax/test_ast.py has a test_role which appears to test internal emphasis. I'm not as familiar with pytest as I need to be, so I had trouble parsing the test suite to figure out exactly what was happening - either way, it doesn't appear the test covers the full conversion from MyST syntax->HTML.

I suggest you take a look at https://myst-parser.readthedocs.io/en/latest/develop/test_infrastructure.html (and obviously let me know if anything of this could be improved to be more helpful). The full conversions are covered in step (4)

So firstly, correct me if I'm wrong, but this is the standard behaviour of parsing rST. The specific [sphinx code is here](https://github.com/sphinx-doc/sphinx/blob/46b4f595ca463159898e8581278cab2e26861df1/sphinx/roles.py#L141), whereby the 'inner node' is a `literal`, i.e. no actual parsing of the text. Maybe an upstream issue could be raised for sphinx.

Secondly, this is currently replicated for Markdown style references here: https://github.com/ExecutableBookProject/MyST-Parser/blob/c64f7068ba786a79561adb0017194ebc8bf15ba3/myst_parser/docutils_renderer.py#L632
Nested syntax is parsed though, but I believe because it is stored on a literal node, you only get the raw text rendered. For example:

```markdown
[*vectorization*](sec:vectorization)
```

gives:

```html
<a class="reference internal" href="ch1.html#sec-vectorization"><span class="std std-ref">vectorization</span></a>.</p>
```

(i.e. the `*` have been removed)

I think this reference style should be able to be improved within this package to do proper nested parsing.

**Comment by rossbar** [comment]
> I suggest you take a look at https://myst-parser.readthedocs.io/en/latest/develop/test_infrastructure.html (and obviously let me know if anything of this could be improved to be more helpful). The full conversions are covered in step (4)

Thanks for the pointer - I missed it on my first pass through the docs (which admittedly was a couple weeks ago). Hopefully I'll be quicker to figure out how to parse the test suite with the additional guidance!

> So firstly, correct me if I'm wrong, but this is the standard behaviour of parsing rST. The specific [sphinx code is here](https://github.com/sphinx-doc/sphinx/blob/46b4f595ca463159898e8581278cab2e26861df1/sphinx/roles.py#L141), whereby the 'inner node' is a `literal`, i.e. no actual syntax parsing of the text. Maybe an upstream issue could be raised for sphinx.

You are correct - the behavior is consistent with the rST parsing. I will take a look through the sphinx issue tracker/PRs to see if this has been raised before.

> 
> Secondly, this is currently replicated for Markdown style references here:
> 
> https://github.com/ExecutableBookProject/MyST-Parser/blob/c64f7068ba786a79561adb0017194ebc8bf15ba3/myst_parser/docutils_renderer.py#L632
> 
> Nested syntax is parsed though, but I believe because it is stored on a literal node, you only get the raw text rendered. For example:
> 
> ```gfm
> [*vectorization*](sec:vectorization)
> ```
> 
> gives:
> 
> ```
> <a class="reference internal" href="ch1.html#sec-vectorization"><span class="std std-ref">vectorization</span></a>.</p>
> ```
> 
> (i.e. the `*` have been removed)
> 
> I think this reference style should be able to be improved within this package to do proper nested parsing.

Good to know, thanks! On the one hand it would be nice if the rST-like syntax and the markdown syntax for references behaved the same, but on the other hand if one syntax can offer more "advanced" features sooner, it may be worth having them be out-of-sync (at least until the lagging syntax catches up).

I'll be sure to try both as I continue to work through converting open source books to MyST syntax.

**Comment by chrisjsewell** [comment]
Cheers, yeh I think the Markdown style syntax is nicer to use in the overall context of the document being markdown. The only potential issue being that this is equivalent to using the [`:any:` role](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-any), which I guess is less specific than using the `:ref:` role.

**Comment by akhmerov** [comment]
It seems markup is now correctly rendered in markdown-style links. Since the `ref`-style links are probably wontfix, should this issue be closed?

`[I am **bold** and mathy $\int$](https://example.com)`

![image](https://user-images.githubusercontent.com/2069677/83350595-65888600-a33d-11ea-813a-793fd5ac839a.png)

**Comment by chrisjsewell** [comment]
> It seems markup is now correctly rendered in markdown-style links

only for external links, see #152
