### ISSUE TITLE
support "download" role

### ISSUE THREAD

**Issue by svenkreiss** [executablebooks/MyST-Parser#144]
Sphinx has a `download` role that I am missing:
https://www.sphinx-doc.org/en/1.3/markup/inline.html#role-download

**Comment by chrisjsewell** [comment]
Thanks for the feedback @svenkreiss, but it seems like you are not aware that myst-parser supports all sphinx roles and directives? (may be related to #81)

**Comment by svenkreiss** [comment]
Using rst syntax for the link seems to work which took me a while to figure out, but that is probably not the intended way for MyST:

```
{download}`help screen <../docs/cli-help-predict.txt>`
```
will create a link called "help screen" and this document will be copied to the `_downloads` folder.

I tried a few variants of `{download}[help screen](../docs/cli-help-predict.txt)` before I figured this out.

**Comment by svenkreiss** [comment]
I see, I didn't know that simply

```
{download}`link/to/file`
```

would work too. That's great. Thanks!

**Comment by chrisjsewell** [comment]
Yep that's exactly the intended way. Using `` :role_name:`content` `` in rST, is directly equivalent to `` {role_name}`content` `` for all roles. They are literally parsed using the same code 😁

**Comment by chrisjsewell** [comment]
(except whenever a role/directive "asks" for nested text to be parsed, it will be parsed as MyST-markdown rather than rST)

**Comment by chrisjsewell** [comment]
I'll close this issue then ta. But feel free to add any opinions in #81 on how you think the documentation could be improved to make this kind of thing clearer.

**Comment by svenkreiss** [comment]
> (except whenever a role/directive "asks" for nested text to be parsed, it will be parsed as MyST-markdown rather than rST)

So in a future version, this might be possible?

```
{download}`[help screen](../docs/cli-help-predict.txt)`
```

**Comment by chrisjsewell** [comment]
Ah no not quite, the content is parsed by the sphinx role: https://github.com/sphinx-doc/sphinx/blob/816c61a81194bc96e99d6e05365aafc9c01b2854/sphinx/util/docutils.py#L417-L435, which specifically hard-code the splitting of the title and link with `<` brackets. So that wouldn't change unless sphinx changed it.
Of course, it is always possible for someone to create their own roles and directives, that could parse the text likes this.

**Comment by choldgraf** [comment]
@chrisjsewell I wonder if this is something we should document somewhere, somehow. I think it's going to confuse people that are familiar with rST, who assume that the contents of a role are just parsed by the same parser that parses the document (as opposed to having syntax that is hard-coded into the role)

**Comment by chrisjsewell** [comment]
Yeh but the syntax that is hard-coded into the role is from the sphinx role, that’s what rST does, it’s not something special to myst

**Comment by choldgraf** [comment]
yeah I know - I just think that most users aren't going to assume that. It's not special to myst, but the mental bug will surface with MyST because users will expect a non-rST syntax to work. Technically the bug is also there when users write rST, it's just that the special syntax that these roles support happens to be the exact same syntax that rST users expect.
