### ISSUE TITLE
Automatically turning raw links into hyperlinks

### ISSUE THREAD

**Issue by asmeurer** [executablebooks/MyST-Parser#166]
This might be a commonmark issue, I'm not sure. When I put a raw link like https://github.com/executablebooks/MyST-Parser/ in a document, it doesn't translate it into a link. I have to write `[https://github.com/executablebooks/MyST-Parser/](https://github.com/executablebooks/MyST-Parser/)`. I would expect links to automatically become hyperlinks, similar to how it works in GitHub or Jupyter notebook Markdown.

**Comment by choldgraf** [comment]
I think this is explicitly not the behavior in CommonMark:

https://spec.commonmark.org/0.29/#example-607

I'll mark this as "enhancement" rather than "bug", since our base assumption is that MyST-NB should behave just like commonmark

**Comment by chrisjsewell** [comment]
I think you need to swat up on your markdown (see https://markdown-it.github.io/), auto-links are `<https://github.com/executablebooks/MyST-Parser/>`

**Comment by choldgraf** [comment]
I think the question is whether we *should* adopt this behavior as an intentional departure from CommonMark, since this is how both Jupyter Markdown as well as GitHub markdown work (and that's what the vast majority of our users will expect):

https://github.github.com/gfm/#autolinks-extension-

**Comment by chrisjsewell** [comment]
> I think the question is whether we should adopt this behavior 

and the answer is, feel free to submit a PR for this extension to markdown-it-py, but I won't be doing because it's a big hassle for the sake of not having to add `<>`, and there are 100 other more pressing  things I could be doing 😜

**Comment by choldgraf** [comment]
so, if this enhancement is in-scope for `markdown-it-py`, and just needs somebody to make a PR, then I'm going to re-open this in case somebody else wants to tackle this PR (unless you want to move this to markdown-it-py). You don't have to personally implement all of the things that are tagged "enhancement", ya know ;-) sometimes it's good to keep feature requests open to see if they gain traction w/ other users

**Comment by chrisjsewell** [comment]
Sure but personally I think it’s a bad idea and shouldn’t be encouraged. It can be certainly be added as a markdown-it-py extension, but it will no doubt negatively affect performance, and will need to be rigorously tested that it actually picks up all url formats which is not a simple task

**Comment by choldgraf** [comment]
that makes sense to me re: performance, I could see the regexes being tricky if we want to mimic GFM behavior. I just think it's worth talking out the pros/cons before closing issues.

**Comment by chrisjsewell** [comment]
cons: it reduces performance, it has a high probability of introducing bugs, it is explicitly flagged as an error in prominent markdown linters: https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md034---bare-url-used

pros: lazy people have to type two fewer characters 😆

**Comment by choldgraf** [comment]
I think one more "pro" is that the vast majority of notebooks that directly input `http` links won't use the `<>` brackets, and their authors won't know the CommonMark spec, so for them they'll think of it as a "bug" in MyST-NB. I think at the least it's something that we should document "this is intentional behavior" in MyST-NB to avoid confusing people

**Comment by chrisjsewell** [comment]
Just point people towards here: https://markdown-it.github.io/

**Comment by chrisjsewell** [comment]
(with commonmark strict selected for the baseline behaviour)

**Comment by choldgraf** [comment]
ehh if people look there, they're going to see this:

![image](https://user-images.githubusercontent.com/1839645/84439705-9003fa00-abed-11ea-9d68-3fb9fec0fea5.png)

looks like they are highlighting this library: https://github.com/markdown-it/linkify-it (which is obviously an extension, but users may not click through or realize that)

**Comment by choldgraf** [comment]
So it seems like the way to support this is:

1. This feature doesn't yet exist and is intentional in the MyST-parser
2. To have this feature with MyST parser, somebody should write a markdown-it-py extension that implements the functionality of https://github.com/markdown-it/linkify-it
3. They should then activate this plugin when they configure their myst-parser as well
4. Or, they can put `<>` around their links

And if they want this functionality without touching Python, they should look into adding javascript to their site that automatically does this, such as https://soapbox.github.io/linkifyjs/

**Comment by chrisjsewell** [comment]
yep sounds good to me 👍

**Comment by asmeurer** [comment]
I didn't know about the <> syntax. I think I've used things where [[https://github.com/executablebooks/MyST-Parser/]] works, but I guess that's non-standard?

I still think it should just autolink links by default.

**Comment by choldgraf** [comment]
@asmeurer see https://github.com/executablebooks/MyST-Parser/issues/166#issuecomment-642934433 for a list of steps to make this work in a Sphinx site. I don't think we have the bandwidth to implement it on the markdown parsing side because it sounds like a big performance hit as well as a really complex set of edge-cases to test. But there should be other ways to implement the functionality in the comment I linked

**Comment by asmeurer** [comment]
The latest release notes now say that linkify is now included with MyST. Can it be enabled by default? I still see this as a major UX failure as it is now, and I would much rather have a slow parser with good UX than the other way around.

**Comment by chrisjsewell** [comment]
yep https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html#linkify

**Comment by chrisjsewell** [comment]
it can be easily enabled, but will not be by default

**Comment by choldgraf** [comment]
Some extra context here, I think that the reasoning for not making it enabled by default is:

1. It is not standard practice for markdown parsers. Neither commonmark, markdown-it, or pandoc markdown support this by default. I can't even find mention of https auto-links [in the github-flavored markdown docs](https://github.github.com/gfm/#links) even though I know auto-linking happens on GitHub. This makes me feel that it is more of a **user interface** feature rather than a markdown parser feature. Moreover, I think that core things like parsers should err on the side of "unopinionated".
2. It is very "web-specific" feature, and MyST is not meant to be a web-specific flavor of markdown.
3. There is a performance hit to parsing these auto-links, though I think it is probably not big

So IMO these are reasonable reasons to start off by just making this feature easy to enable, as has been done and documented in https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html#linkify.

As this seems to be more common in user interfaces than in markdown parsers, one could consider building Sphinx themes that enable this by default, or even that use their own javascript auto-linking script.

**Comment by chrisjsewell** [comment]
> or even that use their own javascript auto-linking script.

Agree with the rest, but I wouldn't advise that
