### ISSUE TITLE
Footnotes render incorrectly in Safari

### ISSUE THREAD

**Issue by mje-nz** [executablebooks/MyST-Parser#196]
**Describe the bug**
On [https://myst-parser.readthedocs.io/en/latest/using/syntax.html](https://myst-parser.readthedocs.io/en/latest/using/syntax.html), the brackets for footnote references aren't superscripted:

<img width="210" alt="Screen Shot 2020-08-05 at 2 43 29 PM" src="https://user-images.githubusercontent.com/6166539/89366077-30782580-d72a-11ea-9f78-5406c751ff3a.png">

and only the brackets for footnote definitions are superscripted:

<img width="259" alt="Screen Shot 2020-08-05 at 2 43 36 PM" src="https://user-images.githubusercontent.com/6166539/89366070-2e15cb80-d72a-11ea-90ba-5d37e2e9611e.png">

**To Reproduce**
1. Go to [https://myst-parser.readthedocs.io/en/latest/using/syntax.html](https://myst-parser.readthedocs.io/en/latest/using/syntax.html) in Safari on macOS or iOS.
2. Observe the footnote references and definitions.

**Environment (please complete the following information):**
- macOS 10.13.6, Safari 13.1.1
- iOS 12.4.1

**Comment by choldgraf** [comment]
@AakashGfude @najuzilu I think this might be related to the latest changes in the citations style?

**Comment by AakashGfude** [comment]
@choldgraf gotcha. one more style rule needs to be updated for safari . On it

**Comment by AakashGfude** [comment]
@choldgraf actually looks like the stylesheet is not updated. 
The style rule committed for citation was:
![Screen Shot 2020-08-05 at 2 25 10 pm](https://user-images.githubusercontent.com/6542997/89371834-c9597180-d727-11ea-9e65-6510df2b503d.png)

But in the browser, it is showing the old one. even after clearing the browser cache : 

![Screen Shot 2020-08-05 at 2 24 46 pm](https://user-images.githubusercontent.com/6542997/89371860-e3934f80-d727-11ea-9c9a-7605a4d7efd0.png)

There is only rule for `.footnote-reference` in `sphinx-book-theme.scss` . so this is strange. Does the cache in CDN needs to be updated for static assets as well? Since, the css file name does not have any hash updates. I won't be surprised if it was cached somewhere in the pipeline.

**Comment by choldgraf** [comment]
hmmm, what does it look like with an incognito window etc?

**Comment by AakashGfude** [comment]
The same with incognito and emptying cache with hard reload.

**Comment by choldgraf** [comment]
hmm - well whenever the next pydata sphinx theme is shipped, they'll start vendoring all (I think) of the CSS and javascript, so that'd mean this isn't an issue anymore, no?

**Comment by AakashGfude** [comment]
> hmm - well whenever the next pydata sphinx theme is shipped, they'll start vendoring all (I think) of the CSS and javascript, so that'd mean this isn't an issue anymore, no?
sorry did not get it. They will start vendoring means? Shipping it? This issue has never come before though right?

**Comment by AakashGfude** [comment]
@choldgraf @mje-nz . The footnote seems to be working fine on this  https://myst-parser.readthedocs.io/en/latest/using/syntax.html one,i.e, being inline.

**Comment by choldgraf** [comment]
re: vendoring, yeah I meant they'll put all of the CSS/JS files bundled with the theme's static files, rather than relying on a CDN.

sounds like this issue may be resolved, though?

**Comment by mje-nz** [comment]
Okay, the footnote definitions haven't changed for me. This is how it looks now:

<img width="210" alt="Screen Shot 2020-08-10 at 10 04 12 AM" src="https://user-images.githubusercontent.com/6166539/89742769-f2478100-daf0-11ea-805f-6f0a5548cc9e.png">
<img width="257" alt="Screen Shot 2020-08-10 at 10 03 24 AM" src="https://user-images.githubusercontent.com/6166539/89742768-efe52700-daf0-11ea-94f5-b4017e614886.png">

**Comment by choldgraf** [comment]
Ah yep - I think you're right @mje-nz. A few notes that I saw:

1. This is only a problem on Safari
2. It does not apply to footnotes in-line with the text, only at the bottom. It only shows up if there are multiple references to the same footnote in the text (so that the `[1]` is not linked, and instead has a `(1, 2)` next to it in superscript.

Here's how it looks in chrome:

![image](https://user-images.githubusercontent.com/1839645/89742963-8fec7300-da53-11ea-832b-cb779b2fc876.png)

here's how it looks in safari (disregard the blurriness):

![image](https://user-images.githubusercontent.com/1839645/89742967-9aa70800-da53-11ea-916a-317efae2091b.png)

**Comment by choldgraf** [comment]
the PR here: https://github.com/executablebooks/sphinx-book-theme/pull/170 fixes the issue on **safari**, but it *introduces* a bug on **chrome**, so I am not sure how to solve both at the same time :-/

I welcome somebody to try fixing this on both safari + chrome - feel free to take over that PR if you wish (or open your own!)

**Comment by AakashGfude** [comment]
Thanks @choldgraf. Is this the bug you are talking about in chrome? : 

![image](https://user-images.githubusercontent.com/6542997/89744788-a6e2a200-daf3-11ea-920f-bd54a7c0a285.png)

**Comment by choldgraf** [comment]
On the chrome side, yes

**Comment by choldgraf** [comment]
should be fixed now! thanks @AakashGfude

**Comment by mje-nz** [comment]
Should it be fixed on [https://myst-parser.readthedocs.io/en/latest/using/syntax.html#myref](https://myst-parser.readthedocs.io/en/latest/using/syntax.html#myref) now? It hasn't changed for me.

**Comment by chrisjsewell** [comment]
just rebuilt the docs

**Comment by choldgraf** [comment]
nah we gotta release a new sphinx-book-theme...I'll do that now.

**Comment by mje-nz** [comment]
Looks good to me, thanks team! :)
