### ISSUE TITLE
Add more `:::{name}` optional syntaxes

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/MyST-Parser#213]
- [ ] topic
- [ ] sidebar
- [ ] glossary

See https://docutils.sourceforge.io/docs/ref/rst/directives.html#body-elements

This would be similar to: https://myst-parser.readthedocs.io/en/latest/using/syntax.html#admonition-directives-special-syntax-optional

**Comment by rkdarst** [comment]
I was wondering, why isn't this supported for arbitrary directives - or at least try to look up arbitrary names and see if they are a subclass of admonition?  I have an extension which adds a lot of slightly customized admonition directives, and it would be nice if they worked here without needing to add to the node_cls.

Background: I am using myst_parser in another Sphinx project, not directly via JupyterBook - and am recommending everyone I know to do the same.

I see I could monkey-patch `myst_parser/docutils_renderer.py:STD_ADMONITIONS` to add them.

I imagine there is some internal reason for this, maybe creating possibly impossible parsing situations, and that's OK.

... edit: it seems it doesn't use normal directive parsing inside, it directly generates the docutils node.  My custom admonitions are based on existing docutils, but I have a custom directive that adjusts some of their properties.  So the current system doesn't work for me at all, it seems...  (probably caused by my limited sphinx skills in making the admonition classes a better way).

**Comment by chrisjsewell** [comment]
Heya, 

> and am recommending everyone I know to do the same.

thanks 😄 

> I imagine there is some internal reason for this

so the current implementation is that for:

````
```{name}
internal *content*
```
````

the internal text is not initially parsed by the Markdown parser.

```python
tokens = [Token(type="fence", content="internal *content*", info="{name}")]
```

the content is then passed directly to the relevant directive class within the myst-parser renderer, to interpret as it wishes.
This then works for every directive.

By contrast,

````
:::{name}
internal *content*
:::
````

will be parsed by the Markdown parser, a bit like:

```python
tokens = [
  Token(type="container_open", info="{name}"),
  Token(type="paragraph_open"),
  Token(type="text", content="internal "),
  Token(type="emphasis", content="content"),
  Token(type="paragraph_close"),
  Token(type="container_close")
]
```

Then the myst-parser renderer "knows" what to do with `Token.type == "container_open"`.
This is handy for directives that fully interpret the internal content as Markdown (mainly admonitions), but naturally will not work for all directives.

>  I have an extension which adds a lot of slightly customized admonition directives

Do you have an example of these directives? what are they actually customizing?
 
In closing this issue, I would like to formalize/generalize a bit how these containers are handled in myst-parser, and perhaps provide a way for people to "hook" in their own types.

**Comment by rkdarst** [comment]
OK, so I see: `:::` is parsed as markdown before being sent to the directive, while ` ``` ` must happen inside of the directive itself (in the case that it is parsed, for example admonitions using ` ``` `).

Maybe I could make sure I understand something correctly: I assumed that `:::` admonitions are made so that, in non-MyST parsers (like Jupyter notebooks), the admonition content and title is shown parsed, so while it doesn't look "right" at least it looks reasonable.  Thus, I would hope that this syntax would work for any kind of directive whose body is internally parsed (but I assume that means raw content needs to be parsed which is done recursively inside the directive)

My custom directives are here: https://github.com/coderefinery/sphinx-lesson/blob/master/sphinx_lesson/directives.py#L17
Despite what it may seem, I'm not actually that good with docutils and I think this isn't written very well.  My first goal was to make actual new node classes, which are then parsed and used.  But instead, I sort of override the base directives and adjust `.run()` so that it sets some classes on a regular admonition node (plus takes an optional title argument).  This is probably a bit hackish, one answer is "fix my directives", but what about the general case?

What happens if the regex `^:::+` gets transparently converted into the equivalent number of backquotes?

Thanks!

**Comment by choldgraf** [comment]
another one to add here might be `epigraph` (https://jupyterbook.org/content/content-blocks.html#quotations-and-epigraphs)

**Comment by choldgraf** [comment]
Another one here could be `{table}` so that people can have tables that have captions, labels etc, and also render in other markdown renderers

**Comment by rkdarst** [comment]
This seems to be "which directives should support `:::`", but my message was "why not everything?".  Why can't `^:::+($|(?!:))` be mapped to ` ```(+) ` at the read-source time?  Any list of extensions myst-parser includes wouldn't include custom extensions that could benefit from it.  If someone enables the option to parse these, it's up to them to decide if it makes sense for any given directive.

I was thinking of making an extension to do this myself, using the `source-read` hook.  I already do this to convert other markdown into myst markdown.

**Comment by rkdarst** [comment]
I'm now slightly less interested, since I wrote my own manual transform along with my other md_transforms:
https://github.com/coderefinery/sphinx-lesson/compare/rkdarst/transform-colons#diff-76d8851fd3cc2f4c27d1e8399cd5d7add6548727992441a00af1691bfb09d8a4R161

... but I partly wrote that as a proof of concept, to see if there are any problems.  I'd still hope that myst_parser could do it "properly", for every directive (in which case I wouldn't use the change I did).  I'm sure there will be some problem cases, but in that case one would simply not use the syntax for the problem cases.

What do you think?  Should I use my custom transform or is there a chance this will work for arbitrary directives?  If others find my transform useful, I could split it off into a separate extension.
