### ISSUE TITLE
Enable display math inside paragraphs

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/MyST-Parser#239]
**Is your feature request related to a problem? Please describe.**

Right now any text which has no line breaks between $$ and the surrounding text is not parsed as a math directive, but rather a math role:

```markdown
line
$$∫$$
another line
```
yields

![image](https://user-images.githubusercontent.com/2069677/91768637-330d5400-ebde-11ea-87af-70a058b92cbf.png)

while 

```markdown
line

$$∫$$

another line
```
correctly renders as

![image](https://user-images.githubusercontent.com/2069677/91768736-618b2f00-ebde-11ea-9e51-36f5a6a3c3f2.png)

I understand that from the spec point of view it makes sense:

- `$$` is a crappy delimiter
- The myst syntax is what it is

However in latex world `$$` is still unfortunately common, and it's seldom separated by newlines (since those mean new paragraphs). Therefore this behavior may be confusing and undesirable. Furthermore the current render result is hard to justify regardless the syntax.

**Describe the solution you'd like**

I'd like to propose relaxing the rules for $$ matches and not expect that they should be separated by blank lines.

Alternatively at the very least I suggest to clearly document the current behavior and warn about it.

**Comment by chrisjsewell** [comment]
It may not quite as simple as relaxing the rule. 
The markdown parser will currently always parse this as a single paragraph. I could recognise, during the inline text parse phase, dollar math with two $, however, this would still end up in the AST as:

```xml
<paragraph>
  Line 1
  <math_block>
    Double dollar math
  Line 3
```

Rather than:

```xml
<paragraph>
  Line 1
<math_block>
  Double dollar math
<paragraph>
  Line 3
```

Which feels like it could have some unexpected side effects

**Comment by akhmerov** [comment]
The former is the correct way to include equations in a latex manuscript (otherwise the text following the equation is indented). Semantically the equation plays the role of a sentence in a paragraph.

Now of course, the HTML rendering may be broken, but that should rather be fixed on the CSS side.

**Comment by chrisjsewell** [comment]
This is not how sphinx math directives work though, so it would inherently be a breaking change to the doctree.
Not to say that I don't agree, but if you want that to be the case, you need to make a PR to sphinx itself.

Its not the job of myst-parser to be adding any CSS

**Comment by akhmerov** [comment]
> Its not the job of myst-parser to be adding any CSS

I know that.

> This is not how sphinx math directives work though, so it would inherently be a breaking change to the doctree.

Good point. I imagine though the problem is rather how text nodes render themselves rather than the limitations of the rst syntax.

Leaving the long-term solution aside, what do you think is the best short-term fix for nonsensical rendering:

![image](https://user-images.githubusercontent.com/2069677/91820532-6f6c9e80-ec36-11ea-9a39-a1cbcb611aaa.png)

**Comment by chrisjsewell** [comment]
It would be relatively easy to add optional (optional) inline `$$` parsing to: https://github.com/executablebooks/markdown-it-py/blob/master/markdown_it/extensions/dollarmath/index.py

Then the behaviour could be controlled by a sphinx option(s), with an option (the default?) being something like this parsing is turned on but it logs a warning

**Comment by akhmerov** [comment]
Good idea.

**Comment by akhmerov** [comment]
A correction about in-paragraph display math breaking the doctree: it's not breaking the doctree.

1. `displaymathrole.py`:
```python
from docutils.nodes import math_block

def display_math_role(role, rawsource, text, lineno, self):
    name = 'displaymath'
    print(role, rawsource, text, lineno, self)
    return [math_block(text, fr"\[{text}\]", nowrap=True)], []

def setup(app):
    app.add_role('displaymath', display_math_role)
    return {"version": "0.0.1", "parallel_read_safe": True}
```

2. `conf.py`:
```python
import sys

sys.path.insert(0, os.path.abspath("."))
master_doc = "index"
extensions = ["displaymathrole", "sphinx.ext.mathjax"]
html_theme = "alabaster"
```

3. `index.rst`:
```rst
Test
----

paragraph starts
:displaymath:`x`
continues
```

4. `sphinx-build . build conf.py`

Produces:

![image](https://user-images.githubusercontent.com/2069677/91990137-a96e9b00-ed31-11ea-940b-15e64d28f06a.png)

![image](https://user-images.githubusercontent.com/2069677/91990171-b7242080-ed31-11ea-841b-59386945a189.png)

**Comment by chrisjsewell** [comment]
cool cheers, 
I suspected it will still "work", but as mentioned above, the doctree will be different for:

```
a
$$b$$
c
```
and
```
a

$$b$$

c
```

which may lead to different/unexpected render results; due to how extensions manipulate the doctree and/or what CSS is applied. So this should definitely still be a "caveated" optional feature

**Comment by jedbrown** [comment]
I run into this often when rendering a static site from Jupyter notebooks. In particular, the extra newlines required for MyST to render correctly introduce extra (unnecessary) vertical space when rendered in a notebook. Since I use the same content for slides (with RISE) and it needs to fit on 16:9 displays, vertical space is precious. Also, I sometimes write the slides live or under time pressure and would like that if it renders correctly in Jupyter/RISE, it'll be somehow reasonable on the JB site.

Is there a way we could make math parsing put display math (via `\begin{equation}` or `$$`) into its own paragraph if needed for correct handling, even when the blank lines don't exist in the source?

**Comment by chrisjsewell** [comment]
This is already closed by `myst_dmath_double_inline = True` (https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#dollar-delimited-math)
