### ISSUE TITLE
Incorrect parsing of math

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/MyST-Parser#240]
**Describe the bug**

Under some circumstances `\,` isn't parsed correctly in a math block

**To Reproduce**

1. Go to https://jupyterbook.org/content/math.html#math-blocks
2. Observe that the first example has an extraneous comma, while the second one doesn't:

![image](https://user-images.githubusercontent.com/2069677/91769830-651fb580-ebe0-11ea-8d3b-2de9a1546f6a.png)

NB: While trying to reproduce, I couldn't manage to get 

```
\begin{equation}
1\,2
\end{equation}
```

to render in a demo book. Does that require some manual action?

**Comment by chrisjsewell** [comment]
This page, and well pretty much the whole of the jupyter-book package and documentation lol, has been re-written in https://github.com/executablebooks/jupyter-book/pull/911, which will very shortly be released as v0.8. So you are probably best off reading from there (or the actual myst-parser docs), since the documentation you are referencing relates to an old version of myst-parser.
See https://deploy-preview-911--jupyter-book.netlify.app/content/math.html 😄 

The key change here is that, now, LaTeX math is parsed directly by markdown-it-py (and converted to `math_block`), rather than by MathJax at the end. This means that (a) it is builder agnostic (i.e. will work with PDF builds), and (b) does not suffer from these escaping artefacts arising from parsing latex around sphinx as raw strings
