### ISSUE TITLE
Make Definition Lists render as Glossaries in Sphinx

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#272]
In Sphinx, one can [use a Glossary](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/glossary.html#create-a-glossary) to define terminology and refer to those terms with ` {term}`My term` `. Our definition lists look almost exactly like a glossary, but don't currently define the terms. Any reason not to make them behave like glossaries?

For example, here's the glossary syntax in MyST:

````md
```{glossary}
My first term
  Some content

My second term
  Some more content
```
````

Whereas here's the same thing with definition lists:

```
My first term
: Some content

My second term
: Some more content
```

**Comment by chrisjsewell** [comment]
I don't think this is a good idea, because definition lists and glossaries are actually distinctly different syntaxes, with glossaries parsed differently, for example with glossaries you can have multiple terms per definition and also add classifiers:

```restructuredtext
.. glossary::

   term1
   term2
       description

   term3 : class2
       description
       description

   term4 : class1
       description
```

Additionally, storing terms for all definition lists could easily lead to duplicate term errors.

You could consider having a separate `glossary-md` directive, but I think thats over complicating things
