### ISSUE TITLE
Add 'console_script' executables for basic document/AST output

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/MyST-Parser#30]
Especially for quick demonstration purposes, without having to hook in to the whole sphinx infastructure. For example `myst-to-ast path/to/doc.md` would convert:

```markdown
# header

Some **bold** text
```

to 

```xml
<document>
    <section>
        header
    <paragraph>
        Some
        <emphasis>
            bold
        text
```

**Comment by choldgraf** [comment]
This would basically just be:

```
from myst_parser.docutils_renderer import DocutilsRenderer
from myst_parser.block_tokens import Document


renderer = DocutilsRenderer()

ast = renderer.render(Document("# Hi"))

print(ast.pformat())
```
right?

Another thought - it would be really cool if we leveraged some interactivity to make it easier to wrap your head around XML. I realized that with a little lightweight library, you can convert XML to an OrderedDict. This lets you use the IPython JSON display library like so:

```
from IPython.display import JSON
import xmltodict

xmld = xmltodict.parse(xml)
JSON(xmld)
```
And you can do stuff like:

![image](https://user-images.githubusercontent.com/1839645/74499279-4d7c2a80-4f37-11ea-9855-b1722a6571df.png)

I wonder if that could be a little helper utility in Myst to wrap the above process.

Now I just need to figure out how to get the docutils AST to output *actual* XML instead of pseudo XML that `pformat` makes :-P  @chrisjsewell any idea on that?

**Comment by chrisjsewell** [comment]
> output actual XML

`documetnt.asdom()`?

**Comment by choldgraf** [comment]
I did a hacky take at this in #37

**Comment by chrisjsewell** [comment]
This is now available as `myst-docutils-psuedoxml`
