### ISSUE TITLE
reStructuredText (RST) renderer

### ISSUE THREAD

**Issue by jpmckinney** [executablebooks/MyST-Parser#310]
**Is your feature request related to a problem? Please describe.**

Sphinx has a ``csv-table`` directive. I have CSVs with Markdown content. I subclassed that directive to rewrite the Markdown as RST (using commonmark). I'd like to be able to do the same with MyST.

**Describe the solution you'd like**

Perhaps a method like `to_rst` that matches the API of `to_docutils`, etc.

**Describe alternatives you've considered**

Right now I'm using commonmark, which has an RST renderer, e.g.:

```python
import commonmark

commonmark.commonmark("Markdown **string**", "rst")
```

See code https://github.com/readthedocs/commonmark.py/blob/master/commonmark/render/rst.py

**Comment by chrisjsewell** [comment]
Yeh its relatively simple to add a markdown-it-py render (see e.g. https://github.com/executablebooks/markdown-it-py/issues/48, https://github.com/executablebooks/markdown-it-py/issues/103 and https://github.com/executablebooks/mdformat/blob/915f2ef4350346065a729a257f3ac81c060a28b1/mdformat/renderer/__init__.py#L16)

For the `csv-table` directive though, I'm not quite sure if I understand your use case, since myst-parser will already parse the Markdown in the CSV?

**Comment by jpmckinney** [comment]
Hmm, you're right; I think maybe the behavior was different in recommonmark. I'll test if I still need this directive subclass.

**Comment by jpmckinney** [comment]
I'll close this for now. I haven't had time to check recently.
