### ISSUE TITLE
Intersphinx cross-ref resolution doesn't work with MyST link syntax

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#325]
**Describe the bug**

It seems that MyST link syntax doesn't work the same way as `{any}` when it uses an intersphinx link. Annoyingly, it also fails silently so there's no warning emitted with `-n` (that I could figure out anyway). The link simply doesn't show up.

**To Reproduce**

I put together a little Sphinx site to demo this:

https://github.com/choldgraf/tmpdemo

The short example is below. I add intersphinx to the `conf.py`, then I add the following in a markdown file:

```md
# Test

(testing)=
## My header

Text

## Another section

See the {ref}`testing`.

See the {any}`testing`.

See the [](testing).

See the {ref}`mnb:installation`.

See the {any}`mnb:installation`.

See the [](mnb:installation).
```

The rendered page looks like this (with no build warnings):

![image](https://user-images.githubusercontent.com/1839645/110675448-bb6d4280-8187-11eb-8d2f-0e2e03ee9c90.png)

**Expected behavior**

I'd expect the link to show up the same way as the explicit `{any}` ref does. Alternatively I'd expect a warning to be emitted because the ref wasn't found.

**Environment**

- Python Version: Latest python from `conda create -n myname python`
- Package versions: See requirements.txt in https://github.com/choldgraf/tmpdemo

**Comment by chrisjsewell** [comment]
You just need to add e.g. `myst_url_schemes=["http", "https"]` to your conf.py (https://myst-parser.readthedocs.io/en/latest/using/intro.html#sphinx-configuration-options), otherwise (because of the colon) myst can't tell whether `mnb:installation` is an external URL or internal reference.
We add this by default in jupyter-book: https://github.com/executablebooks/jupyter-book/blob/5de7ca62541ed4641fb6968c5b58830fec2b5c74/jupyter_book/default_config.yml#L44

To get warnings for this kinda thing you'd need to use the linkcheck sphinx builder

**Comment by choldgraf** [comment]
ahhh interesting - OK I think we should document this as a `gotcha` in the docs since it wasn't obvious (to me at least) that this was related to the url schemes bit.

**Comment by choldgraf** [comment]
@chrisjsewell is there a strong reason not to set `ftp:`, `http:` and `https:` as defaults for that configuration? I feel like those three things would denote 99.9% of URLs people would put in their docs.

**Comment by chrisjsewell** [comment]
Yeh should be fine 😬

**Comment by choldgraf** [comment]
cool, I will try to make a PR for this if I have a moment. I realized that this is an issue for us because we're using `:`  lot in our docs for labels (e.g., `parent:sub-header`)
