### ISSUE TITLE
Duplicate label warnings with a typical `CHANGELOG.md`

### ISSUE THREAD

**Issue by vberlier** [executablebooks/MyST-Parser#337]
I'm trying to include a typical markdown changelog generated by [python-semantic-release](https://python-semantic-release.readthedocs.io/en/latest/) and I'm getting a lot of duplicate label warnings:

    ```{include} ../CHANGELOG.md

    ```

```
project/CHANGELOG.md:20: WARNING: duplicate label feature, other instance in project/docs/changelog.md
project/CHANGELOG.md:23: WARNING: duplicate label fix, other instance in project/docs/changelog.md
project/CHANGELOG.md:31: WARNING: duplicate label feature, other instance in project/docs/changelog.md
project/CHANGELOG.md:36: WARNING: duplicate label fix, other instance in project/docs/changelog.md
...
```

It seems that the warnings happen because it's trying to [create anchors](https://github.com/executablebooks/MyST-Parser/blob/bb0a35f1c28a8ce8ceea94f21624f7804dc14998/myst_parser/sphinx_renderer.py#L108), but because each version has a `Feature` or a `Fix` section I don't really care about having an anchor for any of them.

Is there a way to disable this or at least to silence the warning in this specific situation?

**Comment by chrisjsewell** [comment]
Hey @vberlier, so I assume you are using the `myst_heading_anchors` option (https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html#auto-generated-header-anchors)?

Also you look to be using an older version of myst-parser, because now that warning should show up as: `project/CHANGELOG.md:36: WARNING: duplicate label fix, other instance in project/docs/changelog.md [myst.anchor]`

If so and you update, then you can suppress the `myst.anchor` warnings: https://myst-parser.readthedocs.io/en/latest/using/howto.html#suppress-warnings

**Comment by vberlier** [comment]
Thanks for the quick reply! You just made me realize that the warning was probably emitted by `sphinx.ext.autosectionlabel` because I'm using an up-to-date version of myst-parser. Anyway thanks for the help I should be able to figure things out now 👍
