### ISSUE TITLE
Add nested heading warning

### ISSUE THREAD

**Issue by hukkinj1** [executablebooks/MyST-Parser#351]
Firstly, I'm not really sure whether this ticket is a question, bug report, documentation improvement request, or a feature request, so excuse me if the tag is wrong :smile: 

Anyways, having a heading in an admonition block results in weird, seemingly unexpected/undefined results:
~~~markdown
```{admonition} This is my admonition
# Ooops! This is a heading, not a regular paragraph
```
~~~

The heading is rendered in HTML, but outside the admonition block, in an unexpected location in the doc.

Maybe the set of allowed syntax in an admonition block should be restricted to CommonMark inlines or something? I really don't know.

**Comment by chrisjsewell** [comment]
I really need to write this down somewhere central, because I've explained a similar thing in other contexts (like generating Markdown from code cells).
Its because of the structure of the Sphinx AST, where sections are nested like:

```xml
<section id="h1">
   <section id="h2a">
      <element>
         text
      <section id="h3">
         <element>
   <section id="h2b">
...
```

(you can see this e.g. in the XML files of tests/test_sphinx/test_sphinx_builds/)

If you then try to but a heading inside another element, like an admonition, and then exit that element before exiting the section, you can see how this will mess up the AST structure

```xml
<section id="h1">
   <admonition>
      <section id="h2a">
         <element>
            text
   <section id="h3">
      <element>
   <section id="h2b">
...
```

So technically this is a limitation of Sphinx, that is not something myst-parser can "fix".
Its also only for headings, you certainly would not restict to only inlines because of it.

What can be done I think is to improve warnings around it.
Building this RST file:

```restructuredtext
Document 1 Heading
==================

Document 1 Sub-heading
----------------------

.. note::

   Document 1 Heading
   ==================

   text
```

You will get the warning:

```
doc1.rst:10: WARNING: Unexpected section title.
```

But for the equivalent MyST file there is currently no warning emitted (at least from my quick test):

````markdown
# Document 1 Heading

## Document 1 Sub-heading

````{note}
# Document 1 Heading

text
```

````

**Comment by chrisjsewell** [comment]
Note the "Unexpected section title" warning originates from the docutils parser: https://github.com/chrisjsewell/docutils/blob/8adab0660b2097b4f3c32cef7e5ff4cb3c72b084/docutils/docutils/parsers/rst/states.py#L2761, and is linked to the `match_titles` attribute of the state

**Comment by chrisjsewell** [comment]
essentially I think here: https://github.com/executablebooks/MyST-Parser/blob/ba63021c6eaf447c2d77402b0f6733be94d43095/myst_parser/mocking.py#L126-L142

we should "propagate" the match_titles to the renderer, then here: https://github.com/executablebooks/MyST-Parser/blob/ba63021c6eaf447c2d77402b0f6733be94d43095/myst_parser/docutils_renderer.py#L465

`match_titles is False` should be checked for and dealt with (e.g. emitting a warning)
