### ISSUE TITLE
Reference file specified in `html_extra_path`

### ISSUE THREAD

**Issue by suchun230** [executablebooks/MyST-Parser#361]
**Describe the bug**

My sphinx source directory is located in docs/, and I have a README.md file located in the parent directory, I would like to also include the README.md file into the documentation. So, I created a readme_link.md under docs/ and include the README.md file, follow the guide: https://myst-parser.readthedocs.io/en/latest/using/howto.html?highlight=include#include-a-file-from-outside-the-docs-folder-like-readme-md.
The README.md file has referenced some files also located in the parent directory, as below:
``` 
[reference](reference.txt)
```
The link works well when browsing README.md. However, in documentation build process, warning shows up that the reference target not found during processing the README.md. 
**myproject\README.md:3: WARNING: 'myst' reference target not found: reference.txt**

And the generated readme_link.html file also does not show the link as expected. The link in the html is described as:
```
<p>Check reference file in <span class="xref myst">reference.txt</span></p>
```
I have tried:
1. use relative-docs to rewrite the link. But I do not quite understand the rewrite logic, I changed the reference description to 
```
[reference](./reference.txt)
```
and configure :relative-docs: ./, and I found the warning changes to 
**myproject\README.md:3: WARNING: 'myst' reference target not found: ..\reference.txt**

2. to modify conf.py and added html_extra_path configuration to copy the reference file to the generated html folder, the file is successfully copied to same location of readme_link.html, but there's still no link shows in readme_link.html.
```
html_extra_path = ['../reference.txt']
```

**To Reproduce**

my test project layout:
├── myproject
│   ├── README.md
│   ├── docs
│   │   ├── Makefile
│   │   ├── _build
│   │   ├── _static
│   │   ├── _templates
│   │   ├── conf.py
│   │   ├── index.rst
│   │   └── readme_link.md
│   └── reference.txt

content of README.md
```
# My test project

Check reference file in [reference.txt](reference.txt)
```
content of index.rst
```
Welcome to myproject's documentation!
=====================================

.. toctree::
   :maxdepth: 1
   :caption: Contents:

   readme_link.md
```
content of readme_link.md
```
  ```{include} ../README.md
  :relative-docs: docs/
  :relative-images

```
I am working on windows, so using mingw32-make for sphinx documentation generation, run "ming32-make html" could reproduce the below warning:
 
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
writing output... [100%] readme_link
C:\work\SDK\sdk-github\repowork\test-docs\bug_report\myproject\README.md:3: WARNING: 'myst' reference target not found: reference.txt
generating indices...  genindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 1 warning.

The HTML pages are in _build\html

**Expected behavior**

link to reference.txt is not broken in readme_link.html

**Environment**

- Python Version : 3.9.0
- myst-parser: 0.13.5
- Operating System:

**Additional context**

**Comment by chrisjsewell** [comment]
thanks for the feedback, I've changed this to an enhancement rather than a bug, because currently referencing files (in any context) will only work for other source files, e.g. if you were referencing `reference.md` or `reference.rst` this should work fine, but I don't believe there is any inherent was in Sphinx to reference arbitrary files.

**Comment by suchun230** [comment]
Hi @chrisjsewell, thanks for timely reply. I see same issue referencing reference.md. I have tried to not using myst_parser, changed the source to rst, which is README.rst and readme_link.rst, even though I see same warning, but there's link show in readme_link.html, however the linked is invalid because file not found. After I enabled html_extra_path to copy the needed files, I could access the link successfully.

**Comment by jpmckinney** [comment]
You can also use the download role to refer to files that Sphinx is otherwise unaware of:

```
{download}`text <reference.txt>`

**Comment by chrisjsewell** [comment]
> I see same issue referencing reference.md

Ah yes, well additionally the `reference.md` would need to be inside the `docs` folder, i.e. so that sphinx identifies it as a source document

But anyhow I am going to fold this into #193

**Comment by jgoeders** [comment]
I had the same issue where we had `/doc/src` documentation, as well as files at the top-level, like `README.md` and `BUILDING.md`, and we wanted to:
  1. Link between Markdown files in `/doc/src` (normal myst-parser behavior)
  2. Include top-level Markdown files in your Sphinx build, and allow them to link to files in `/doc/src`
  3. Link from files in `/doc/src` to top-level Markdown files
  4. Link between top-level Markdown files (so that the links work when browsing on Github, as well as when included in the Sphinx build)

## Steps to Make this Work:


### 1. Link between files in `/doc/src`

This is just usual internal myst-parser linking discussed at <https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html#markdown-links-and-referencing>

### 2. Link from top-level Markdown files to files in `/doc/src`

For each top-level documentation file, add a stub Markdown file in your docs source, for example, I have a `/doc/src/BUILDING.md` file, and the contents of the file are:

    ```{include} ../../BUILDING.md
    :relative-docs: doc/src
    ```

With this stub file, you should be able to include these top-level Markdown files in your Sphinx build and their links will work.  Just point at the stub files in your toctree.  For example, your *index.rst* could contain:

    .. toctree::
     
        README
        BUILDING
        some_other_rst_page

 Even if you have subdirectories with *index.rst* files, you can still point up to the stub files (`../BUILDING`).


### 3. Link from files in `/doc/src` to top-level Markdown files

At this point you can link to your top-level Markdown files by simply linking to the stub files using normal internal myst-parser links.  

For example, the file `/doc/src/mydir/info.md` could contain:

    This is a [link to the readme](../README.md)

Or, from an RST file such as `/doc/src/mydir/info.rst`:

    This is a :doc:`link to the readme </README>`

###  4. Link between top-level Markdown files (so that the links work when browsing on Github)

You can continue to link between top-level Markdown files as usual, and the links will work when viewed on Github, or when included in your Sphinx build:

In `README.md`:

    See build instructions [here](BUILDING.md)

**Comment by jpmckinney** [comment]
Noting that (2) above is (now?) documented at https://myst-parser.readthedocs.io/en/latest/sphinx/use.html#include-a-file-from-outside-the-docs-folder-like-readme-md
