### ISSUE TITLE
Optional, but on by default syntax

### ISSUE THREAD

**Issue by hukkin** [executablebooks/MyST-Parser#399]
Why does MyST have optional syntax that is on by default. At least dollarmath is like this, and it feels counter intuitive to me. I'd expect anything that is on by default to be part of "core" MyST syntax.

If nothing else, I think this sentence should be fixed in the docs:
> The following syntaxes are optional (disabled by default)

**Comment by chrisjsewell** [comment]
See https://github.com/executablebooks/mdformat-myst/pull/9#issuecomment-867055932;
It’s only dollarmath and that’s mainly for legacy reasons and a deprecation pathway is a bit of a pain

**Comment by choldgraf** [comment]
Yeah - to @chrisjsewell's point this is one reason that we moved dollarmath to the "optional" page in the latest docs refactor (#385 I believe). IMO it is less confusing to have an "optional syntax" that is "on by default" rather than to document an "optional syntax" in the "core syntax" page.

Maybe we should just add a quick note about this here: https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#math-shortcuts

Something like

```
:::{note}
Dollar math is **on by default** even though it is an optional syntax.
This is because of its common use across many markdown formatters, and for legacy purposes.
We may revisit whether to consider this as part of "core" syntax in the future.
:::
```

?
