### ISSUE TITLE
Add support for strikethrough

### ISSUE THREAD

**Issue by nemani** [executablebooks/MyST-Parser#405]
**Is your feature request related to a problem? Please describe.**

While markdown-it-py seems to support strikethrough, looks like myst_parser does not. 
I tried to enable it locally in `main.py` but then it errored saying there is not rule to render `s`.
Docutils doesnt have any node for the same, so not sure how to go about adding it. 

**Describe the solution you'd like**

Strikeout should work by rendering a `<s> </s>` or `<del> </del>` tags

**Comment by chrisjsewell** [comment]
Heya, yeh its a bit of pain, because unfortunately docutils/sphinx does not directly support strike-through,
e.g. for bold/strong text we can directly convert it to a `nodes.strong(*child_nodes)` AST object, then sphinx will handle converting that to the output format (HTML, TeX, ...).
For strike-through then MyST would currently have to use a custom node like `nodes.strikethrough(*child_nodes)`, then also provide the default logic for the different output formats.
When using specific HTML themes as well, it may also get tricky, because they will likely not have any specific CSS to handle this.

I would certainly like to have it, but ideally this would be an upstream addition to docutils/sphinx.

**Comment by choldgraf** [comment]
Perhaps as a start this could be a simple "sphinx-strikethrough" package that would add a strike through inline node via a role, and this could be an optional deoendency for the Myst parser similar to the linkify syntax?

**Comment by chrisjsewell** [comment]
the `strikethrough` extension has now been available for a while: https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#strikethrough
