### ISSUE TITLE
Detect changes in included files

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/MyST-Parser#415]
According to https://github.com/executablebooks/MyST-Parser/issues/414#issuecomment-897906643_, sphinx does actually do this for standard `include` directives (I haven't yet personally tested this).

In myst-parser we have to override the standard directive: https://github.com/executablebooks/MyST-Parser/blob/61f1154f232c89d5e8d17ca56616e42e328db7eb/myst_parser/mocking.py#L315.
This generally works fine, but maybe I missed some code, to "tell" sphinx about the included files?

**Comment by webknjaz** [comment]
I was just about to file a bug about this. My use-case was that I included a `README.md` from the repo root into `docs/index.md`. I'm able to make Sphinx notice the changes by `rm -rf`ing the doctrees directory.

I haven't checked why MyST-Parser fails to pick up the changed files but I assume that it may be caused by forgetting to call `note_dependency()` from within the directive. In one of my projects, I had to track the files manually like this: https://github.com/sphinx-contrib/sphinxcontrib-towncrier/blob/c760f36/src/sphinxcontrib/towncrier/__init__.py#L244-L358 + https://github.com/sphinx-contrib/sphinxcontrib-towncrier/blob/c760f36/src/sphinxcontrib/towncrier/__init__.py#L204.

**Comment by webknjaz** [comment]
Oh, I think that this is because `note_included()` at
https://github.com/executablebooks/MyST-Parser/blob/61f1154f232c89d5e8d17ca56616e42e328db7eb/myst_parser/mocking.py#L361 is withing a try-except block. If any of the first two instructions fail, that line is skipped and never executed.

*I think* that it should be moved outside of try-except (after it) or even further, to make this robust.

**Comment by chrisjsewell** [comment]
thanks for looking it, yeh you had to note it as a dependency as well as an included
