### ISSUE TITLE
Output nested headings as rubric

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/MyST-Parser#494]
This should be a quick fix when I'm back at my computer. 

When a nested parse is called, e.g. by an admonition directive, `match_title` is set to `False` by default. 
(See https://github.com/live-clones/docutils/blob/bd16bdb302f5b24340ddaa69d109d419886bf0ac/docutils/docutils/parsers/rst/states.py#L257)

Then, when a heading underline is encountered in RST, this makes it ignore that heading and just log a warning
(https://github.com/live-clones/docutils/blob/bd16bdb302f5b24340ddaa69d109d419886bf0ac/docutils/docutils/parsers/rst/states.py#L2419)

Currently in myst-parser, an error is correctly logged, but also the heading is still parsed. This can really mess up the resulting AST structure.
Instead of ignoring it though, I think it would be a nice behaviour to still log the warning (which can be suppressed in sphinx) but then output the heading as a rubric, which does not affect the AST structure.

**Comment by danieleades** [comment]
how does this interact with the `nested_parse_with_titles` method (as opposed to `nested_parse`)?

**Comment by chrisjsewell** [comment]
Hey @danieleades well then `match_title` should be equal to `True`, so then this is bypassed

**Comment by danieleades** [comment]
> Hey @danieleades well then `match_title` should be equal to `True`, so then this is bypassed

Thanks for the quick response! I'll test this now. Right now my custom directive is using `nested_parse`, the directive content contains headings, and the Myst parser is throwing warnings. The real issue though, is the warnings text is visible inline in the rendered html output...

**Comment by danieleades** [comment]
`nested_parse_with_titles` solves it for me!

**Comment by danieleades** [comment]
> `nested_parse_with_titles` solves it for me!

@chrisjsewell - I take it back. `nested_parse_with_titles` appears to insert the subheadings and their text into the document as siblings *next to* the directive content, rather than as *part of* the directive content. So it appears that this method is *not* a drop-in replacement for `nested_parse`.

I'm a little stumped. I have a sphinx bug report and a reproduction described here - https://github.com/sphinx-doc/sphinx/issues/11001. While I'd appreciate any advice you can offer, I think this is a sphinx problem, rather than a Myst problem.
