### ISSUE TITLE
can't parser image base64

### ISSUE THREAD

**Issue by wannianhong** [executablebooks/MyST-Parser#514]
### Describe the bug

markdown 

`![xxx](data:image/png;base64,ixxxxx)`

myst-parser can't parser

### Reproduce the bug

markdown 
`![xxx](data:image/png;base64,ixxxxx)`
myst-parser can't parser

**Comment by wannianhong** [comment]
`markdown 
![xxx](data:image/png;base64,ixxxxx)
myst-parser can't parser`

**Comment by eyllanesc** [comment]
@wannianhong I don't think it's a bug since markdown doesn't support base64 by default, and I don't see MyST pointing to that feature either. One potential solution is to implement a plugin as shown in[ this example](https://markdown-it-py.readthedocs.io/en/latest/architecture.html#renderer) but unfortunately it seems that you can't add new plugins to the MarkdownIt object used by the project.

**Comment by chrisjsewell** [comment]
yes indeed this is not a feature currently supported by myst-parser, and not something planned. PRs are welcome though
