### ISSUE TITLE
Line wrapped $math$ confuses the parser

### ISSUE THREAD

**Issue by asmeurer** [executablebooks/MyST-Parser#562]
### Describe the bug

**context**

Consider the following text

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa $x(x(x(x(x(x + 3) - 2) + 1)
- 1) - 3) + 1$.
```

My text editor has automatically line wrapped it to 80 characters. The expression at the end should be rendered as LaTeX math, but instead, it rendering the math on the first line as plain text, and the stuff on the second line as bullet points.

<img width="619" alt="Screen Shot 2022-05-02 at 4 57 43 PM" src="https://user-images.githubusercontent.com/71486/166339718-429cef52-8423-4b58-88c3-764a05219111.png">

**problem**
This is a problem because text editors automatically hard wrap text, so the parser should not render text differently if it is line wrapped.

### Reproduce the bug

Create a Markdown document with the above text

### List your environment

I am using myst-parser 17.2 with Sphinx 4.4.0.

**Comment by chrisjsewell** [comment]
This is not possible in CommonMark, lists always interrupt paragraphs: https://spec.commonmark.org/0.30/#example-303

**Comment by choldgraf** [comment]
To add some extra context to this, the problem is specifically that your new line happens to also begin with a `- ` character. So the parser detects this and concludes that a new paragraph needs to be started (per the commonmark spec that @chrisjsewell linked above).

A way to get around this would be to ensure that the second line doesn't start with `- `. For example:

```
Testing one $two
three$.

Testing one $two
-three$.

Testing one $two
- three$.

Testing one $two
three - four$.
```

results in:

![image](https://user-images.githubusercontent.com/1839645/166868706-fb1ae670-d60a-4321-b2ba-a54927e1b1c4.png)
