### ISSUE TITLE
Mermaid sequence diagram does not render in docs website

### ISSUE THREAD

**Issue by andy-t-sp** [executablebooks/MyST-Parser#725]
### Describe the bug

**context**
When I go to this webpage https://myst-parser.readthedocs.io/en/latest/intro.html#extending-sphinx

**expectation**
I expected sequence diagram rendering to occur.

**bug**
But instead the diagram source code is displayed.
Here's what is shown on the screen:
![image](https://user-images.githubusercontent.com/117356826/221880261-2d97b3c6-73ed-4180-960d-3437e44401fd.png)

**problem**
This is a problem for people reading the docs because it is meant to showcase what is possible.

### Reproduce the bug

1. Go to: https://myst-parser.readthedocs.io/en/latest/intro.html#extending-sphinx and view the visible code that is there instead of the rendered diagram.

### List your environment
Chrome Version 110.0.5481.104 (Official Build) (64-bit) on Windows 10

_No response_

**Comment by chrisjsewell** [comment]
Hi @andy-t-sp thanks for the feedback, but I'm actually already updating the docs in #717 
check it out: https://myst-parser--717.org.readthedocs.build/en/717/index.html

I've actually removed mermaid for now though, due to: https://github.com/mgaitan/sphinxcontrib-mermaid/issues/109
Maybe give them a gentle nudge to fix it 😅

**Comment by andy-t-sp** [comment]
Thanks for the quick reply, @chrisjsewell apologies for reporting something you are already working on, thanks for the link to the bug report in sphinxcontrib-mermaid. I am having a similar issue in my own docs, so thank you!
